spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
        show_sql: true
  datasource:
    username: root
    password: MySQLRootPassword
    url: jdbc:mysql://:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
server:
  port: 8080

indexing-settings:
  sites:
    - url: https://et-cetera.ru/mobile/
      name: EtCetera
    - url: http://www.playback.ru/
      name: Playback
#    - url: https://www.svetlovka.ru/
#      name: Svetlovka
#    - url: https://shm.ru/
#      name: Исторический музей
#     - url: https://ipfran.ru/
#       name: Physic institute of Gaponov Grehov
